trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '7fb67d67-5fb5-41b5-939f-c362f86574e5'
  imageRepository: 'app1/app1nginx'
  containerRegistry: 'aksdevopsacr11.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default   # self-hosted agent pool
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)